### PR TITLE
Github Action: gradle build action added

### PR DESCRIPTION
**Pull request by nt1dc**

### CODE REVIEW

**Comment by kamilchulakov** [comment]
FEATURE = не просто FEATURE, а MOVIE, CONTEXT, etc, DEVELOPMENT, согласно DEVELOPMENT.md

**Comment by kamilchulakov** [comment]
push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

**Comment by kamilchulakov** [comment]
checkout v3

**Comment by kamilchulakov** [comment]
bad file name

**Comment by nt1dc** [comment]
> push: branches: [ "master" ] pull_request: branches: [ "master" ]

build only on master  ?_?

**Comment by kamilchulakov** [comment]
> > push: branches: [ "master" ] pull_request: branches: [ "master" ]
> 
> build only on master ?_?

add something like all

**Comment by nt1dc** [comment]
> > > push: branches: [ "master" ] pull_request: branches: [ "master" ]
> > 
> > 
> > build only on master ?_?
> 
> add something like all

it's actually  now )

**Comment by nt1dc** [comment]
@kamilchulakov approve pls

**Comment by nt1dc** [comment]
ура!

**Pull request merged**
