### PR TITLE
DEVELOPMENT : create packages + add description to DEVELOPMENT.md

### PR DESCRIPTION
**Pull request by nt1dc**

### CODE REVIEW

**Comment by nt1dc** [comment]
@kamilchulakov  approve?)

**Comment by kamilchulakov** [comment]
Please rename commit to DEVELOPMENT:

**Comment by nt1dc** [comment]
> Please rename commit to DEVELOPMENT:

pr name changed

**Comment by kamilchulakov** [comment]
> > Please rename commit to DEVELOPMENT:
> 
> pr name changed

you've update pr name but not commit message

**Comment by nt1dc** [comment]
finally

**Pull request merged**
